channels:
  conda-forge
dependencies:
  - pip
  - pip:
      - pip install numpy jupyter-server-proxy "jupyterlab>=1.0" jupyterlab-dash==0.1.0a3 jupyterlab_iframe bokeh jupyter_bokeh
    - code-server