dependencies:
  - conda-forge::jupyterlab>=1.0
  - conda-forge::numpy
  - conda-forge::jupyter-server-proxy
  - conda-forge::code-server
  - conda::bokeh
  - conda::jupyter_bokeh
  - conda::plotly
  - conda-forge::jupyterlab-dash=0.1.0a3
